// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvwzajcuxedoggmrwsvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2d3phamN1eGVkb2dnbXJ3c3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTQwOTMsImV4cCI6MjA2NzEzMDA5M30.vWmwY_7iHXJSy9OnYzUEARy_SaHRGRgdcZdMAY-Bbq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});